In [25]:
import numpy as np

v = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])

v

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [6]:
v[0,1,3]

2

In [13]:
np.zeros((3,2,4))

#Podríamos decir que el tres representa los 3 grupos (Array)
#El 2 representa las filas de cada grupo (Array)
#El 4 las columnas de cada grupo (Array)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
v + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [17]:
np.mean(v)

6.458333333333333

In [26]:
np.sum(v,axis=1)

array([[10, 12, 13,  7],
       [10, 15, 15,  8],
       [18, 17, 19, 11]])

In [22]:
np.shape(v)

(3, 2, 4)